# Test Configuration for the MLOps Predictive Maintenance Project

data:
  processed_data_dir: "data/processed_test"
  target_column: "RUL"
  test_size: 0.2
  val_size: 0.15
  random_state: 42
  database_path: "turbofan_test.sqlite"

model:
  name: "predictive_maintenance_model_test"
  params:
    objective: "reg:squarederror"
    eval_metric: "rmse"
    n_estimators: 10
    learning_rate: 0.1
    max_depth: 3

tuning:
  n_trials: 2
  objective_metric: "rmse"
  direction: "minimize"

mlflow:
  experiment_name: "Predictive Maintenance Test"
  registry_uri: "databricks-uc"

visualization:
  output_dir: "visualizations_test"